version: '3.1'
services:
    syngrisi-app:
        container_name: syngrisi-app-server
        restart: always
        # command: tail -f /dev/null
        command: sh -c "node server.js"
        build:
            context: .
            dockerfile: syngrisi-app.dockerfile

        ports:
            - "${SYNGRISI_DOCKER_PORT:-5000}:3000"
        volumes:
            # /syngrisi/baselines
            - "${SYNGRISI_DOCKER_IMAGES_PATH:-./baselines}:/usr/src/syngrisi/baselines"
            - "${SYNGRISI_DOCKER_BACKUPS_PATH:-./backups}:/usr/src/syngrisi/backups"
        depends_on:
            - 'syngrisi-db'
        logging:
            driver: 'json-file'
            options:
                max-size: '100m'
                max-file: '10'
        environment:
            SYNGRISI_DB_URI: "${SYNGRISI_DB_URI:-mongodb://syngrisi-db/VRSdb}"
            SYNGRISI_IMAGES_PATH: "${SYNGRISI_IMAGES_PATH:-./baselines/}"
            SYNGRISI_AUTH: "${SYNGRISI_AUTH:-1}"
            SYNGRISI_TEST_MODE: "${SYNGRISI_TEST_MODE:0}"
            SYNGRISI_APP_PORT: 3000

        healthcheck:
            test: [ "CMD", "mongo", "${SYNGRISI_DB_URI:-mongodb://syngrisi-db/VRSdb}", " --eval", "'db.runCommand(\"ping\").ok'" ]
            interval: 1m30s
            timeout: 10s
            retries: 3

    syngrisi-db:
        image: mongo:4.2.21
        container_name: syngrisi-db-server
        ports:
            - "${SYNGRISI_DB_DOCKER_PORT:-27017}:27017"
        command: [ "--bind_ip_all", "${SYNGRISI_DOCKER_DB_AUTH_ARG:---noauth}" ]
        restart: always
        volumes:
            - "${SYNGRISI_DOCKER_DB_PATH:-./data/db_data}:/data/db"
        environment:
            MONGO_INITDB_ROOT_USERNAME: "${MONGODB_ROOT_USERNAME}"
            MONGO_INITDB_ROOT_PASSWORD: "${MONGODB_ROOT_PASSWORD}"
